### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by lioyou** [yangjianxin1/GPT2-chitchat#1]
> 虽然使用了多轮历史对话作为响应的生成条件，但是chatbot还是不能很好地掌握该逻辑。而Sample3与Sample5中，chatbot无法知道自己“是否在南京”，“是否去过北京”。 Sample6和Sample7这种重复性的问题（用户重复输入一样的对话内容），也无法识别一致的答案。

多次提问，产生不同的答案，生成逻辑中，使用了`torch.multinomial`函数，即使生成的概率是一样的，产生相同的答案，但是经过这个函数抽样后，结果也有可能不同啊，这个函数不是为了多样性而使用的吗？

**Comment by yangjianxin1** [comment]
@lioyou 是的，解码器那部分是为了生成的response的多样性。关于那个不足，我想表达的是"这个chatbot只是记住了汉字的概率分布，还没有掌握上下文的逻辑"。

**Comment by lioyou** [comment]
那请问，生成的测试，是在没有使用`torch.multinomial and topp`的条件下吗？因为这两个都会使结果产生多样性，另外目前所有模型基本是无法达到掌握上下文逻辑的，如果有，也只是训练的语料包含了相关内容，结果体现是可能在某个对话中表现得比较好，但是事实是不具备通用性，除非模型足够大，训练的内容覆盖广，质量也好的情况下，模型的表现可能好些。但是要真正达到所谓的理解逻辑，这个...

**Comment by yangjianxin1** [comment]
@lioyou 有些样例是指定了topp参数生成的，有些没有。贴一个刚刚通过命令python interact.py --no_cuda --max_history_len 5 --topp 0.8跑出的一个sample，效果也还不错。关于逻辑这个问题，确实如此，就算强如微软小冰也做的不是很好。

user:你好
chatbot:你好
user:在干嘛呢
chatbot:在想你呢
user:好害羞啊
chatbot:害羞什么啊
user:你这样夸我，我觉得不好意思呀
chatbot:我夸你你还不好意思呢
user:是啊，哈哈哈
chatbot:你是不是在考验我
user:你怎么会这样想呢
chatbot:我说我在夸你，这么客气，
user:你有睡午觉吗
chatbot:有啊
user:我现在有点困呢
chatbot:我也是
user:等下还要去上课，好烦啊
chatbot:我们不用上课的呀

**Comment by lioyou** [comment]
就单纯的问答而言，提高语料质量，特别对于一些专业性的回答，相信可以表现得很好，特别是具有规范的格式，如法律条文查询之类的回答，或者诗歌之类的，所以过分强调逻辑没必要，即使是人，表达有时也无法连贯，因为我们会遗忘，而模型的表现是：它没有学习过（训练语料没有）所以要想模型结果好一些，语料很重要，这是提高所谓的逻辑表现好一点的一种方式。
不过呢，作者训练的这个模型也不错~谢谢你的分享

**Comment by yangjianxin1** [comment]
@lioyou 是的，谢谢你的建议~

**Comment by lioyou** [comment]
建议谈不上，交流想法，仅此而已
