### ISSUE TITLE
GPT-2 预训练

### ISSUE THREAD

**Issue by zlinao** [yangjianxin1/GPT2-chitchat#11]
谢谢作者分享中文对话语料， 我想请问一下训练对话模型之前， 有用大量文本预训练GPT吗

**Comment by yangjianxin1** [comment]
@zlinao 模型是从零开始训练的，没有用预训练模型，目前GPT2官方也没有中文预训练模型

**Comment by netblind** [comment]
假设我用中文语料训练，设置的epoch是30，每个epoch结束保存一次模型，我想问一下，如果我在第10个epoch结束后发生故障，程序停止了，可不可以我再继续训练的时候接着第10个epoch训练？

**Comment by yangjianxin1** [comment]
@netblind 可以的，可以指定--pretrained_model参数，加载预训练模型
