### ISSUE TITLE
ignore_index 的设置

### ISSUE THREAD

**Issue by xuyouqian** [yangjianxin1/GPT2-chitchat#116]
大佬您好，整理您的代码发现 对于ignore_index的label token不计算梯度这个默认的设置是100 但是100 对应的是个uncased 99 这个是不是可以不用设置，这里面有需要忽略梯度的单词吗

**Comment by yangjianxin1** [comment]
ignore_index的默认值是-100



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月6日(星期四) 下午3:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [yangjianxin1/GPT2-chitchat] ignore_index 的设置 (Issue #116)





 
大佬您好，整理您的代码发现 对于ignore_index的label token不计算梯度这个默认的设置是100 但是100 对应的是个uncased 99 这个是不是可以不用设置，这里面有需要忽略梯度的单词吗

**Comment by xuyouqian** [comment]
不好意思  才看到那个地方 
    input_ids = rnn_utils.pad_sequence(batch, batch_first=True, padding_value=0)
    labels = rnn_utils.pad_sequence(batch, batch_first=True, padding_value=-100)
    这两个设置的不一样是为啥啊

**Comment by xuyouqian** [comment]
我看到后面的逻辑了  不好意思  T.T
