### ISSUE TITLE
根据效果显示，多轮对话的效果貌似不明显

### ISSUE THREAD

**Issue by vcbeaut** [yangjianxin1/GPT2-chitchat#13]
![微信截图_20200104180748](https://user-images.githubusercontent.com/22236673/71764009-816a3600-2f1d-11ea-97e5-8d7e9a9c4ba9.png)

**Comment by yangjianxin1** [comment]
我自己用interact.py和interact_mmi.py生成了几个sample，效果大致上还行。你生成的样例没有用到mmi，interact_mmi.py生成的效果会更好一些。也可以尝试加大batch_szie，在公开的模型的基础上继续训练。

下面两个是用interact.py生成的sample：

**Sample1：**
user:想看你的美照
chatbot:我也想看你美照
user:我亲两口
chatbot:么么哒
user:亲我一口就给你看
chatbot:哈哈哈

**Sample2：**
user:想看你的美照
chatbot:因为你没有女朋友
user:我亲两口
chatbot:哈哈哈哈哈哈哈
user:亲我一口就给你看
chatbot:哈哈哈

然后用interact_mmi.py生成了几个样例：

**Sample1：**
user:想看你的美照
candidate response:
哈哈，我不是一直在你家吗 loss:2.5620837211608887
没发现我的丑吗 loss:2.5463879108428955
我就是你们的 loss:2.6249985694885254
我就是我 loss:2.425882577896118
我也好想看你的美照 loss:1.7035661935806274
chatbot:我也好想看你的美照
user:我亲两口
candidate response:
好的 loss:2.157503366470337
可以的 loss:2.2499547004699707
好呀好呀 loss:2.061696767807007
么么 loss:2.1231181621551514
哈哈哈 loss:2.0661234855651855
chatbot:好呀好呀
user:亲我一口就给你看
candidate response:
么么么哒 loss:2.2150821685791016
那就来 loss:2.34334659576416
你真的好想跟你嗦粉丝的脚步 loss:2.5939981937408447
给你一个大大的么么哒 loss:1.9243746995925903
好啊 loss:2.2188475131988525
chatbot:给你一个大大的么么哒

**Sample2：**
user:想看你的美照
candidate response:
哈哈我就算偷懒也要发也要偷懒 loss:3.65812611579895
我也想看你的美照 loss:1.6144483089447021
就这样子看我的就不说话了？！ loss:3.3027520179748535
哈哈哈哈，我的我就算了 loss:2.584864854812622
我怕我的美照把你拍丑了 loss:2.0793046951293945
chatbot:我也想看你的美照
user:我亲两口
candidate response:
可以的哈哈哈哈 loss:1.9073163270950317
好的我收到了 loss:1.9790791273117065
完全抽象 loss:2.697998523712158
哈哈哈哈好等我有空了就去找你哈 loss:1.9393807649612427
可怕 loss:2.1300570964813232
chatbot:可以的哈哈哈哈
user:亲我一口就给你看
candidate response:
那就来吧 loss:2.2379751205444336
我接受你的不接受你的专属 loss:2.240915060043335
我要看小哥哥 loss:2.0767061710357666
亲你一口我就跟你走 loss:2.23250675201416
那不行我还是吃你的醋 loss:2.5006461143493652
chatbot:我要看小哥哥

**Comment by yangjianxin1** [comment]
我自己用interact.py和interact_mmi.py生成了几个sample，效果大致上还行。你生成的样例没有用到mmi，interact_mmi.py生成的效果会更好一些。也可以尝试加大batch_szie，在公开的模型的基础上继续训练。

下面两个是用interact.py生成的sample：

**Sample1：**
user:想看你的美照
chatbot:我也想看你美照
user:我亲两口
chatbot:么么哒
user:亲我一口就给你看
chatbot:哈哈哈

**Sample2：**
user:想看你的美照
chatbot:因为你没有女朋友
user:我亲两口
chatbot:哈哈哈哈哈哈哈
user:亲我一口就给你看
chatbot:哈哈哈

然后用interact_mmi.py生成了几个样例：

**Sample1：**
user:想看你的美照
candidate response:
哈哈，我不是一直在你家吗 loss:2.5620837211608887
没发现我的丑吗 loss:2.5463879108428955
我就是你们的 loss:2.6249985694885254
我就是我 loss:2.425882577896118
我也好想看你的美照 loss:1.7035661935806274
chatbot:我也好想看你的美照
user:我亲两口
candidate response:
好的 loss:2.157503366470337
可以的 loss:2.2499547004699707
好呀好呀 loss:2.061696767807007
么么 loss:2.1231181621551514
哈哈哈 loss:2.0661234855651855
chatbot:好呀好呀
user:亲我一口就给你看
candidate response:
么么么哒 loss:2.2150821685791016
那就来 loss:2.34334659576416
你真的好想跟你嗦粉丝的脚步 loss:2.5939981937408447
给你一个大大的么么哒 loss:1.9243746995925903
好啊 loss:2.2188475131988525
chatbot:给你一个大大的么么哒

**Sample2：**
user:想看你的美照
candidate response:
哈哈我就算偷懒也要发也要偷懒 loss:3.65812611579895
我也想看你的美照 loss:1.6144483089447021
就这样子看我的就不说话了？！ loss:3.3027520179748535
哈哈哈哈，我的我就算了 loss:2.584864854812622
我怕我的美照把你拍丑了 loss:2.0793046951293945
chatbot:我也想看你的美照
user:我亲两口
candidate response:
可以的哈哈哈哈 loss:1.9073163270950317
好的我收到了 loss:1.9790791273117065
完全抽象 loss:2.697998523712158
哈哈哈哈好等我有空了就去找你哈 loss:1.9393807649612427
可怕 loss:2.1300570964813232
chatbot:可以的哈哈哈哈
user:亲我一口就给你看
candidate response:
那就来吧 loss:2.2379751205444336
我接受你的不接受你的专属 loss:2.240915060043335
我要看小哥哥 loss:2.0767061710357666
亲你一口我就跟你走 loss:2.23250675201416
那不行我还是吃你的醋 loss:2.5006461143493652
chatbot:我要看小哥哥

**Comment by vcbeaut** [comment]
@yangjianxin1 train.py 280行input_ids.to(device) 应该改为input_ids.to(device)，不然CUDA环境没有转入GPU上。

**Comment by yangjianxin1** [comment]
@vcbeaut thanks
