### ISSUE TITLE
您好，我今天用别的语料进行训练，出现了以下问题，请您有空帮忙解答

### ISSUE THREAD

**Issue by xuexiaona** [yangjianxin1/GPT2-chitchat#14]
2020-01-08 14:18:13,763 - INFO - loading traing data
2020-01-08 14:18:13,806 - INFO - total training steps = 162195
Traceback (most recent call last):
  File "train.py", line 432, in <module>
    main()
  File "train.py", line 426, in main
    train(model, device, train_list, multi_gpu, args)
  File "train.py", line 263, in train
    scheduler = transformers.WarmupLinearSchedule(optimizer, warmup_steps=args.warmup_steps, t_total=total_steps)
AttributeError: module 'transformers' has no attribute 'WarmupLinearSchedule'

**Comment by yangjianxin1** [comment]
应该是transformers的版本问题吧？试试2.1.1，看看会不会报错

**Comment by xuexiaona** [comment]
谢谢，弄好了

**Comment by vcbeaut** [comment]
可以不换版本，用from transformer import get_linear_schedule_with_warmup

**Comment by ECNUHP** [comment]
> 2020-01-08 14:18:13,763 - INFO - loading traing data
> 2020-01-08 14:18:13,806 - INFO - total training steps = 162195
> Traceback (most recent call last):
> File "train.py", line 432, in
> main()
> File "train.py", line 426, in main
> train(model, device, train_list, multi_gpu, args)
> File "train.py", line 263, in train
> scheduler = transformers.WarmupLinearSchedule(optimizer, warmup_steps=args.warmup_steps, t_total=total_steps)
> AttributeError: module 'transformers' has no attribute 'WarmupLinearSchedule'

您好，想问一下您，在训练的时候您用的预训练的参数文件是作者在网盘里提供的吗？

**Comment by icegomic** [comment]
> 应该是transformers的版本问题吧？试试2.1.1，看看会不会报错

可以  换了2.1.1就行了
