### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by zcuuu** [yangjianxin1/GPT2-chitchat#19]
作者您好，我在服务器上运行训练代码
python3 train.py --epochs 30 --batch_size 1 --device 0 --raw

Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:08.0 Off |                    0 |
| N/A   54C    P0   246W / 300W |  15514MiB / 16130MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:00:09.0 Off |                    0 |
| N/A   38C    P0    39W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000000:00:0A.0 Off |                    0 |
| N/A   29C    P0    39W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  On   | 00000000:00:0B.0 Off |                    0 |
| N/A   30C    P0    38W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

gpu 0 是tf 在跑的代码，
我运行就出错
RuntimeError: CUDA error: out of memory
向您请教

**Comment by woainifanfan** [comment]
out of memory 问题 要么你内存不过降低下batch_size ,要么你还在训练其他模型 使用CUDA 并没有把cuda内存释放干净 ，nvidia-smi 查看的并不是实时的内存状态
