### ISSUE TITLE
关于网盘

### ISSUE THREAD

**Issue by Monica9502** [yangjianxin1/GPT2-chitchat#2]
你好，请问有数据和模型的Google drive链接嘛？因为网络限制，不能打开百度云，非常感谢~

**Comment by yangjianxin1** [comment]
@rachelMmmmm 不好意思，这个数据暂时还没上传到google drive，我上传了再告诉你。

**Comment by yangjianxin1** [comment]
@rachelMmmmm 不好意思，让你久等了，我已经将数据集和预训练模型上传到了GoogleDrive
