### ISSUE TITLE
MMI的算法与原论文是否存在出入

### ISSUE THREAD

**Issue by NarrownessSmasher** [yangjianxin1/GPT2-chitchat#22]
尊敬的作者：
       您好！
       您的代码中，总是将输入作为label来计算loss，我总觉得这样做虽然也可以产生不差的效果，但与原论文中所阐述的，用答句来预测问句P(Source|target)还是有一定区别的。我谨以为相应的部分需要稍微改进一下，将前向计算的label设为输入对话之前的问答部分，是否是我的理解出现了偏差呢，还请不吝赐教！

**Comment by NarrownessSmasher** [comment]
理解失误，抱歉！

**Comment by Reveyer** [comment]
我也觉得有问题，
```
 out = mmi_model(input_ids=mmi_input_tensor, labels=mmi_input_tensor)
 loss = out[0].item()
```
这里只计算了一个loss，也就是
![image](https://user-images.githubusercontent.com/39128351/83935562-45e5d780-a7ed-11ea-8e52-c77ffe6e2741.png)
而不是 P(source|target)

原文中是P(source|target)，P(target|source)及 N_t 的线性组合

**Comment by Reveyer** [comment]
也不对，代码中是计算生成最后一个SEP的loss

**Comment by huangdacheng** [comment]
> 尊敬的作者：
> 您好！
> 您的代码中，总是将输入作为label来计算loss，我总觉得这样做虽然也可以产生不差的效果，但与原论文中所阐述的，用答句来预测问句P(Source|target)还是有一定区别的。我谨以为相应的部分需要稍微改进一下，将前向计算的label设为输入对话之前的问答部分，是否是我的理解出现了偏差呢，还请不吝赐教！

您好  我也对代码中对MMI的实现 存在疑问， 为什么看起来 对mmi model的训练 和dialog model的训练，除了语句的顺序之外 没有什么差别
