### ISSUE TITLE
如何控制生成的文本是短文本的？

### ISSUE THREAD

**Issue by netblind** [yangjianxin1/GPT2-chitchat#28]
你好，想请教一下是怎么实现的让生成的文本是短文本？是因为训练的语料都是短文本吗？

**Comment by yangjianxin1** [comment]
主要是因为训练语料大多是短文本，在代码方面没有对生成长度进行显式的控制

**Comment by ForLittleBeauty** [comment]
你好，我发现生成的长度被限制到了25，所有的句子都像是被截断了一样，可以请教一下原因吗

**Comment by yangjianxin1** [comment]
> 你好，我发现生成的长度被限制到了25，所有的句子都像是被截断了一样，可以请教一下原因吗

生成长度是超参数，可以自己指定
