### ISSUE TITLE
批量生成建议

### ISSUE THREAD

**Issue by lioyou** [yangjianxin1/GPT2-chitchat#3]
可以利用past加快生成及添加批量生成，如果你后面的Future Work完成，则可以通过批量，同时生成一些句子，然后进行评分选出最优解
批量生成：
```python 
input_ids = [tokenizer.cls_token_id]  # 每个input以[CLS]为开头
# 在此位置添加一行
inputs = [copy.deepcopy(input_ids) for _ in range(batch_size)]` # 这行作为输入，转成Tensor
```
https://github.com/yangjianxin1/GPT2-chitchat/blob/master/interact.py#L149 这行更改为
`next_token_logits = outputs[0][:,-1, :]`
这行https://github.com/yangjianxin1/GPT2-chitchat/blob/master/interact.py#L88 干掉
接下来要更改generated=[[] for _ in range(batch_size)] 变成二维数组接收结果
```python
 generated.append(next_token.item()) # 变成以下这样子
[l.append(next_token[i].item()) for i,l in enumerate(generate)]
```
后面的连接也要改一下
纯属建议...

**Comment by yangjianxin1** [comment]
@lioyou 非常感谢，最近比较忙，有空了我会修改一下代码
