### ISSUE TITLE
数据预处理过慢

### ISSUE THREAD

**Issue by Wh2018** [yangjianxin1/GPT2-chitchat#31]
作者您好，我找到一个您提到的50W对话数据集的完整版，包含500W个轮对论对话，但是使用preprocess_raw_data处理成token的时候速度非常慢，一晚上才处理了十万条，请问有什么解决方法么
![Snipaste_2020-04-04_09-44-00](https://user-images.githubusercontent.com/35520082/78416090-dfabcf80-7658-11ea-92e5-b96dd1d44598.png)

**Comment by yangjianxin1** [comment]
用BertTokenizer进行tokenize的速度确实很慢，可以尝试[HuggingFace的新项目tokenizers](https://github.com/huggingface/tokenizers)

**Comment by ZhuoranLyu** [comment]
> 作者您好，我找到一个您提到的50W对话数据集的完整版，包含500W个轮对论对话，但是使用preprocess_raw_data处理成token的时候速度非常慢，一晚上才处理了十万条，请问有什么解决方法么
> ![Snipaste_2020-04-04_09-44-00](https://user-images.githubusercontent.com/35520082/78416090-dfabcf80-7658-11ea-92e5-b96dd1d44598.png)

改一下
https://github.com/yangjianxin1/GPT2-chitchat/blob/ded94e086b3ad35f951563356b907bb9d7842e99/train.py#L142
这里的if顺序

**Comment by DavidLanz** [comment]
请问500W多轮对话能在哪找到呢?

**Comment by Wh2018** [comment]
> 请问500W多轮对话能在哪找到呢?

http://tcci.ccf.org.cn/conference/2018/taskdata.php
NLPCC2018的数据集
