### ISSUE TITLE
请问一下你的loss再训练后降到多少了

### ISSUE THREAD

**Issue by gmftbyGMFTBY** [yangjianxin1/GPT2-chitchat#33]
训练结束的时候的 loss 和 acc 大致在一个什么范围呢，谢谢啦

**Comment by ZhuoranLyu** [comment]
我的loss降到2.多就差不多能用了

**Comment by gmftbyGMFTBY** [comment]
@yangjianxin1 不知道如果提前使用大规模的非对话平行语料来训练语言模型，之后在对话平行语料上fine-tune会不会收敛更快，速度更好？

**Comment by gmftbyGMFTBY** [comment]
@ZhuoranLyu 我也是差不多

**Comment by ZhuoranLyu** [comment]
> @ZhuoranLyu 我也是差不多

你不如直接在作者提供的模型上finetune一下就行 很方便

**Comment by yangjianxin1** [comment]
@gmftbyGMFTBY loss降到2.0左右，模型生成的对话，效果还不错

**Comment by zyds** [comment]
@yangjianxin1 您好，我想问一下，loss降到2.0左右，是指的训练集上的loss吗？验证集上的loss大概是多少呢？

**Comment by jmfu95** [comment]
@ZhuoranLyu 您好，请问Loss降到2.0训练时间需要多久？还有您的服务器是一个什么配置？

**Comment by ZhuoranLyu** [comment]
> @ZhuoranLyu 您好，请问Loss降到2.0训练时间需要多久？还有您的服务器是一个什么配置？

30 epochs 服务器看你自己 我是dgx
