### ISSUE TITLE
请问temperature的作用

### ISSUE THREAD

**Issue by lx999** [yangjianxin1/GPT2-chitchat#35]
作者你好，我在代码中看到下一个logits会除以temperature，但是它是整体都除以这个temperature，不知道这一步骤有什么作用，希望回答，感谢~
(然后还有一个小问题在采样的时候除了multinomial，不知道其他的你试过没有，或者有没有什么建议)

**Comment by yangjianxin1** [comment]
当temperature趋向0的时候，采样方式趋向于贪婪采样。当temperature趋向正无穷的时候，采样方式趋向均匀采样

**Comment by alphadl** [comment]
t的大小和模型最终模型的正确率没有直接关系，我们可以将t的作用类比于学习率。我们的label类似于[1,0,0]，最“尖锐”，如果我们在训练时将t设置比较大，那么预测的概率分布会比较平滑，那么loss会很大，这样可以避免我们陷入局部最优解。
