### ISSUE TITLE
模型可以合并么？

### ISSUE THREAD

**Issue by runcarry** [yangjianxin1/GPT2-chitchat#37]
训练好的多个模型，怎么合并成一个模型

**Comment by GinSoda** [comment]
简单来说
`
class model(transformers.PretrainedModel):
    def __init__(self, config, model_a, model_b):
        super().__init__(config)
        self.partA= model_a
        self.partB= model_b
`

**Comment by GinSoda** [comment]
```
class model(transformers.PretrainedModel): 
    def __init__(self, config, model_a, model_b): 
        super().__init__(config) 
        self.partA= model_a 
        self.partB= model_b
```
