### ISSUE TITLE
请问gradient_accumulation这个参数是啥意思？

### ISSUE THREAD

**Issue by Years-Enron** [yangjianxin1/GPT2-chitchat#40]
gradient_accumulation默认值为1，当我改为大于1的时候发现loss下降的很快....

**Comment by yangjianxin1** [comment]
gradient_accumulation是用来进行梯度累计，当内存不足时，batch_size无法设置得比较大，训练效果会比较差。可以用梯度累计，改善这个问题

**Comment by Years-Enron** [comment]
> gradient_accumulation是用来进行梯度累计，当内存不足时，batch_size无法设置得比较大，训练效果会比较差。可以用梯度累计，改善这个问题

谢谢大佬解答

**Comment by GinSoda** [comment]
简单来说，每反向传播n次（取平均），进行1次梯度下降

**Comment by Years-Enron** [comment]
非常感谢

GinSoda <notifications@github.com> 于 2020年11月20日周五 下午8:31写道：
