### ISSUE TITLE
请问您提供的预训练model在50W对话上训练前，用其他数据集预训练过吗？

### ISSUE THREAD

**Issue by Zyh716** [yangjianxin1/GPT2-chitchat#42]
请问您提供的预训练model在50W对话上训练前，用其他数据集预训练过吗？如果没有的话，能否提供一下在THUCNews这样的数据集上预训练的思路吗，万分感谢

**Comment by yangjianxin1** [comment]
分享的预训练模型，只是使用了50w的数据集进行训练
