### ISSUE TITLE
50万模型网盘链接失效

### ISSUE THREAD

**Issue by zzh-ecnu** [yangjianxin1/GPT2-chitchat#5]
中文50万训练的模型网盘链接失效了哦。

PS：Epoch跑十轮是不是基本和四十轮差不多？Batch Size 8的设定是测试出来的吗？

谢谢解答~

**Comment by yangjianxin1** [comment]
@zzh-ecnu 在readme中更新了链接地址，最新的readme中的地址是可以访问的。batch size设为8主要是怕显存不够用，怕OOM，设大一点应该会更好一些，你可以尝试一下。可能是因为batch size设为了8，所以loss下降的比较慢，训练10轮和40轮的差距还是很大的。
