### ISSUE TITLE
tokenizer输入问题

### ISSUE THREAD

**Issue by xCerisier** [yangjianxin1/GPT2-chitchat#54]
https://github.com/yangjianxin1/GPT2-chitchat/blob/ded94e086b3ad35f951563356b907bb9d7842e99/interact.py#L138

请问这里为什么使用tokenizer.encode(text)而不是像train过程中一样循环使用convert_tokens_to_ids(word)呢？这样history中的每一句都变成了[CLS] u [SEP]，最终生成的时候输入不就是变成了[CLS][CLS]u1[SEP][CLS]u2[SEP]...[SEP]吗？

**Comment by huu3301** [comment]
transfromer2.1.1版本以后的tokenizer.encode(text)会在前自动加上[CLS]，后加上[SEP]，但2.1.1版本不会
