### ISSUE TITLE
gpt2中文预训练模型

### ISSUE THREAD

**Issue by ChengchengDu** [yangjianxin1/GPT2-chitchat#58]
您好 中文预训练模型是您训练diag-model的checkpoint吗？不是想bert那样在大规模通用语料上训练的模型吗？

**Comment by yangjianxin1** [comment]
> 您好 中文预训练模型是您训练diag-model的checkpoint吗？不是想bert那样在大规模通用语料上训练的模型吗？

可以直接拿dialogue model的那个模型用，但是这个模型只是在50w多轮对话的语料上训练的，没有使用大规模通用语料
