### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by echoyes** [yangjianxin1/GPT2-chitchat#6]
请问安装好环境之后，执行python train.py --epochs 30 --batch_size 8 --device 0,1 --raw
直接爆出一个Segmentation fault (core dumped)，任何错误提示都没有，咋回事呢？多谢

**Comment by yangjianxin1** [comment]
@echoyes 提交代码之前我跑过一遍，好像可以正常tokenize。我晚点再跑一下，看看是什么问题。可以把报错信息贴一下吗？

**Comment by echoyes** [comment]
> @echoyes 提交代码之前我跑过一遍，好像可以正常tokenize。我晚点再跑一下，看看是什么问题。可以把报错信息贴一下吗？

解决了，主要是import transformers的时候会触发Segmentation fault (core dumped)，这个在https://github.com/scipy/scipy/issues/11237 和 https://github.com/huggingface/transformers/pull/2207 有讨论，我把scipy由1.4.0降级为1.3.3就OK了

**Comment by yangjianxin1** [comment]
我的scipy==1.2.1，所以没有报错，我在requirements里加一下

**Comment by echoyes** [comment]
> 我的scipy==1.2.1，所以没有报错，我在requirements里加一下

是的，pip install sklearn的时候会默认安装scipy的最新版

**Comment by yuanliping** [comment]
降级scipy就行了
