### ISSUE TITLE
提升对话的速度

### ISSUE THREAD

**Issue by brook-w** [yangjianxin1/GPT2-chitchat#66]
如何提升对话的速度呢 现在每次对话 都在1.2s 以上甚至更多 如果调参需要调哪些参数
尽可能的提高回答的速度？？

**Comment by SweetDream-0913** [comment]
请问您这个问题解决了吗？我刚接触，也碰到这个问题，只用dialogue_model平均每次会话1s左右，加上mmi_model后，平均每次会话5s左右~

**Comment by WuMianRen** [comment]
没有奥  有别的闲聊的模型或者开源项目吗 一起研究下

**Comment by WuMianRen** [comment]
> 请问您这个问题解决了吗？我刚接触，也碰到这个问题，只用dialogue_model平均每次会话1s左右，加上mmi_model后，平均每次会话5s左右~

**Comment by SweetDream-0913** [comment]
没有呀，我也是刚接触这块的内容，测试了一下时间，发现和您有相同的问题呢

**Comment by WuMianRen** [comment]
https://github.com/WuMianRen/funNLP 看下这个项目对你有没有用处 还有你是做什么的方面的技术的（单纯问问）

**Comment by WuMianRen** [comment]
> 没有呀，我也是刚接触这块的内容，测试了一下时间，发现和您有相同的问题呢

**Comment by SweetDream-0913** [comment]
谢谢您的分享，这个里面好像没有提升GPT2预测速度的方法，我不是主要做NLP方面的，只是我们现在的工作中涉及到闲聊库这边的东西，所以才来学习的~

**Comment by WuMianRen** [comment]
这里面是没有提升GPT2预测的  但是有其他的闲聊模型  和一些可以直接使用的闲聊的接口 应该可以完成你的需要  不一定非要使用 GTP2 里面有很多一些优秀的 闲聊项目 除非你对 GTP2 有特别情节 哈哈哈

**Comment by yangjianxin1** [comment]
去掉了mmi的生成方式，在CPU上跑，response的生层速度也还可以。

**Comment by WuMianRen** [comment]
好 谢谢了  非常需要  等我重新安装测试一下  大佬 给力
