### ISSUE TITLE
引入mmi后是否效果更好？需要同时加载两个模型？

### ISSUE THREAD

**Issue by jianfengzhai** [yangjianxin1/GPT2-chitchat#7]
我测试了两种情况的，发现有些未必会有改善。另外，后者需要加载两个模型么？

测试例子如下：
都输入 开始吧 作为起始
case1结果：
开始吧
chatbot:怎么就开始了呢
user:时间到啦啊
chatbot:嗯呢
user:嗯什么
chatbot:嘿嘿，开心一下
user:傻样子
chatbot:哪里傻，我还是个宝宝
user:哪哪都傻
chatbot:你这自信我就不开心了，大妹子，你也不是大妹子了
case2结果：
聊天记录2019-12-19 15:33:20.506588:
user:开始吧
candidate response:
我会让你认真的 loss:4.256475925445557
前面都是乱拍 loss:5.4540791511535645
好像是吧 loss:4.401147842407227
想哭 loss:5.471364974975586
开始，没法回头看 loss:4.7793965339660645
chatbot:我会让你认真的
user:时间到啦啊
candidate response:
就剩两天了 loss:4.653099536895752
上课无聊的我 loss:4.549105644226074
哈哈 loss:4.642543315887451
没有错！ loss:4.593847751617432
哼！好好好 loss:4.555785655975342
chatbot:上课无聊的我
user:嗯什么
candidate response:
回来吧 loss:4.875833034515381
早点睡吧，还要熬夜 loss:4.683757305145264
要放假 loss:5.102223873138428
还有下课呀 loss:4.945773601531982
没事儿就好好上课 loss:4.674844741821289
chatbot:没事儿就好好上课
user:傻
candidate response:
我没有 loss:4.917065143585205
上着呢啊 loss:4.985911846160889
我不信 loss:4.801839351654053
打死你 loss:4.787909984588623
谁不是 loss:4.949956893920898
chatbot:打死你
user:傻样子
candidate response:
玩游戏就傻了 loss:4.653222560882568
别打我，我还不知道你的脆皮脸呢 loss:4.488063335418701
可爱的小师妹 loss:4.773369789123535
大哥，真不知道是谁，哈哈哈 loss:4.318464756011963
真心的好不做作 loss:4.669813632965088
chatbot:大哥，真不知道是谁，哈哈哈
聊天记录2019-12-19 16:10:18.691453:
user:开始吧
candidate response:
我希望他能像我一样有个像刘诗诗一样有个性的男朋友， loss:3.41839599609375
我是真的认为她要走了就不能这样玩了 loss:3.9923839569091797
咋了 loss:5.471773147583008
不开心 loss:5.102871894836426
没错 loss:5.399983882904053
chatbot:我希望他能像我一样有个像刘诗诗一样有个性的男朋友，

**Comment by yangjianxin1** [comment]
对的，后者需要使用到两个模型

关于你在上面贴出来的样例的效果，我是这样理解的：
1、我分享的预训练模型，只是使用了67M，50w个多轮对话训练，可能有些对话场景没有涵盖，就比如上面的一些对话。
2、你在上面贴出来的例子的MMI模型的loss都比较大，基本都在3以上，甚至是5，应该是dialogue model生成的candidate response就挺差的，要让MMI modol在“差中选优”，最终的response的效果应该也好不到哪里。
3、你可以看看我贴出来的几个例子的MMI模型的loss都基本在2左右，dialogue model生成的candidate response的效果应该还是不错的。在“优中选优”，效果应该会更好。比如下面这个例子，“周末要一起出去玩吗”，在各个candidat response中，“可以，你还是做老师吗”的MMI loss是最大的，直观上来说确实也是效果最差的response。因此也被MMI model排除掉了
4、添加了MMI model之后，可能有些最终的response效果确实变差了，但是个人感觉总体上还是有提升的。

我们可以继续交流一下想法

user:周末要一起出去玩吗
candidate response:
可以呀 loss:2.0150623321533203
可以呀 loss:2.0150623321533203
可以，你还是做老师吗 loss:2.2639517784118652
可以啊 loss:1.9695569276809692
周末要 loss:2.1701855659484863
chatbot:可以啊

user:我好想你啊
candidate response:
我也好想你啊 loss:1.8660272359848022
那我们就可以一起出来玩呀 loss:2.046417236328125
我也好想你啊 loss:1.8660272359848022
我也很久没出去玩啦 loss:2.17940354347229
来找我吧 loss:2.14339542388916
chatbot:我也好想你啊

user:爱你么么哒
candidate response:
么么哒 loss:1.6875463724136353
好想你可是也不着急了 loss:2.2054319381713867
么么哒 loss:1.6875463724136353
你会爱上新花园的人吗 loss:2.521526575088501
我也爱你 loss:1.6839145421981812
chatbot:我也爱你

**Comment by jianfengzhai** [comment]
你好，明白，我想问下这两个模型是同样的语料训练出来的么？如果是，我测试的是输入相同的上文，加入mmi没有提升反而差了，……
因为没有打印出加入之前的loss，最好打出来，针对相同输入对比一下是否会更有说明意义呢？

发自我的 iPhone

**Comment by echoyes** [comment]
我用自己的语料训练，其实就是[CLS]Q[SEP]A[SEP], loss降到1.25，acc0.72, 是不是已经基本上收敛了？但是一个epoch还没跑完。大概一共500w对QA。还有就是这个ACC是带有teacher forcing的acc 吗

**Comment by yangjianxin1** [comment]
@jianfengzhai 这个在readme中有介绍，两个模型是使用同一个语料训练的。关于"我测试的是输入相同的上文，加入mmi没有提升反而差了"这个问题，我觉得：
1、可能是在没加入mmi模型时，恰好生成了一个比较好的response
2、加入了mmi模型后，生成的5个候选response都没有那么好，可以尝试加大--batch_size参数生成多几个候选response，我默认是生成5个
3、mmi模型可能还没有训练的很好？可以尝试继续训练一下

比如有一条训练数据：
想看你的美照
亲我一口就给你看
我亲两口
讨厌人家拿小拳拳捶你胸口

训练dialogue model的输入为"[CLS]想看你的美照[SEP]亲我一口就给你看[SEP]我亲两口[SEP]讨厌人家拿小拳拳捶你胸口[SEP]"

训练mmi model的输入为"[CLS]讨厌人家拿小拳拳捶你胸口[SEP]我亲两口[SEP]亲我一口就给你看[SEP]想看你的美照[SEP]"

也就是说dialogue model和mmi model的拼接顺序是相反的

**Comment by yangjianxin1** [comment]
@echoyes 这个loss挺好的，我之前训练过一个金庸小说的文本生成，loos降到1.0-1.2左右，生成效果就挺不错的。这个acc指的是，根据上文的tokne预测出下一个token的准确率。

**Comment by echoyes** [comment]
> @echoyes 这个loss挺好的，我之前训练过一个金庸小说的文本生成，loos降到1.0-1.2左右，生成效果就挺不错的。这个acc指的是，根据上文的tokne预测出下一个token的准确率。
你的loss到1.0左右训练了多久啊？我大概用4块p40训练了2小时loss就降到了1.8左右。
还有就是后续会有BLEU评估的脚本吗？想看一下BLEU score

**Comment by yangjianxin1** [comment]
@echoyes 我之前训练的模型参数和现在这个对话模型的参数不一样，n_ctx设置的是1024，现在对话这个模型的n_ctx我设了300。金庸小说那个用了两块1080Ti，数据集是金庸的小说，raw data是25M，进行tokenize之后数据还挺大的，跑了八九个小时吧。最近年底比较多事情忙，暂时还没考虑添加一些新功能或进行大修改，要到1月多才比较有空。如果你有什么建议的话，希望多交流，也可以pull

**Comment by chin-gyou** [comment]
@yangjianxin1  你好，如果对话大小达到接近1个G，但平均轮数和项目中的训练数据差不多，请问你觉得设置上有哪些需要调整呢？用项目中的参数设置训练，loss在2.9附近下降不动了（已训练十多个epoch）。

**Comment by yangjianxin1** [comment]
@chin-gyou loss的下降是比较慢的，如果显存够用的话，可以尝试加大batch_szie，loss应该会降得快一些。我训练的时候由于显存限制，batch_size设为了8，loss降到2.0，也花了三四十个epoch
