### ISSUE TITLE
UNK请教

### ISSUE THREAD

**Issue by lioyou** [yangjianxin1/GPT2-chitchat#9]
对于模型来说，出现UNK应该是比较罕见的情况，https://github.com/yangjianxin1/GPT2-chitchat/blob/master/interact_mmi.py#L171 不应该在此处理，也没有必要处理，如果一个模型很容易就产生UNK，那表明模型在训练的时候，数据分词后存在许多UNK，这是不合理的，根本原因是分词采用的分词表设计得不好或词汇太少。
如中文，可以添加单字到词表，以保证所有句子可以正确分割成最基本的单字，而不会产生UNK
而英文，就是单字母了。
**当然这样可以完全避免UNK吗？**
视情况而定，语料如果参杂太多的字词，词表又太少，那UNK就无法避免，所以训练前，数据预处理非常重要，可以根据要求去除无关词，如只要中文，那其它的就不应该被放进模型，如英文，日文等，而繁写的在预处理数据时，就要转成简体。另外，生成时的一些敏感词或不想生成的东西，就不应该放到模型中，在数据预处理时，就应该过滤掉。
如果你有什么不同的见解，请指教。

**Comment by yangjianxin1** [comment]
代码里将UNK的概率设为Inf，是为了避免最终产生UNK，你说的在训练时先对数据进行预处理，是个不错的做法。

**Comment by lioyou** [comment]
产生UNK的根本原因就是：训练时有太多（占极大比例）词表中没有的词，所以生成时也极有可能产生UNK。那么当进行预处理时，就需要尽可能将UNK降低，当UNK占比很少时，生成时产生UNK的概率几乎为0，所以没有必要进行判断。
如果一个模型极易产生UNK，是不合理的，词表设计绝对有问题。
所以设置概率为Inf，不能从根本上解决问题，反而是在掩盖问题！

**Comment by yangjianxin1** [comment]
如果在训练前，针对自己的数据集，自建一个新的词表，只要词表够大，基本就不会产生UNK了。

**Comment by lioyou** [comment]
对的，不过词表不用非常大，覆盖常用词就行了，毕竟是一个占比问题，如果UNK占比小，就不会产生此问题。
