### ISSUE TITLE
模型训练不动了

### ISSUE THREAD

**Issue by G-Jarvey** [yangjianxin1/GPT2-chitchat#91]
您好，我在使用100w的数据集进行训练时，loss和acc初始为10与0，进行到第10个epoch就降到了3左右和40左右，现在是第18个epoch，基本没有任何下降，想请教一下可能是什么原因导致的呢，这种属于正常情况吗，还要继续训练下去吗

**Comment by G-Jarvey** [comment]
另外想问一下作者的loss降到2左右时的acc大概是多少啊

**Comment by G-Jarvey** [comment]
loss还有小幅度的下降，但是准确率基本没变了

**Comment by yangjianxin1** [comment]
主要还是看loss下降。acc太大了反而会使得生成的丰富度降低。
