### ISSUE TITLE
raise HTTPError(http_error_msg, response=self)

### ISSUE THREAD

**Issue by Mather10** [yangjianxin1/GPT2-chitchat#92]
How to fix the error below

 ```
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/model_epoch40_50w/resolve/main/config.json
```

when running "python interact.py --model_path model_epoch40_50w --device 0"? Thanks.

**Comment by yangjianxin1** [comment]
模型不存在，下载我上传的模型，然后修改模型路径参数

**Comment by Mather10** [comment]
Thank you for your reply. Which file that you uploaded do you mean specifically? Is it the pkl file? Thanks.

**Comment by yangjianxin1** [comment]
模型分享：model_epoch40_50w
